<?
/**
 * @package LLA.Base
 */
$GLOBALS['cnt_list'] = array(
'US' => 'United States', 'AF'=>'Afghanistan',
'AL' => 'Albania', 'DZ' => 'Algeria', 'AS' => 'American Samoa', 'AD' => 'Andorra',
'AO' => 'Angola', 'AI' => 'Anguilla', 'AG' => 'Antigua & Barbuda', 'AR' => 'Argentina',
'AM' => 'Armenia', 'AW' => 'Aruba', 'AU' => 'Australia', 'AT' => 'Austria', 'AZ' => 'Azerbaijan',
'AP' => 'Azores', 'BS' => 'Bahamas', 'BH' => 'Bahrain', 'BD' => 'Bangladesh', 'BB' => 'Barbados',
'BY' => 'Belarus', 'BE' => 'Belgium', 'BZ' => 'Belize', 'BJ' => 'Benin', 'BM' => 'Bermuda',
'BT' => 'Bhutan', 'BO' => 'Bolivia', 'BL' => 'Bonaire', 'BA' => 'Bosnia & Herzegovina',
'BW' => 'Botswana', 'BR' => 'Brazil', 'BN' => 'Brunei', 'BG' => 'Bulgaria', 'BF' => 'Burkina Faso',
'BI' => 'Burundi', 'KH' => 'Cambodia', 'CM' => 'Cameroon', 'CA' => 'Canada', 'IC' => 'Canary Islands',
'CV' => 'Cape Verde', 'KY' => 'Cayman Islands', 'CF' => 'Central African Republic', 'TD' => 'Chad',
'CL' => 'Chile', 'CN' => 'China, People\'s Republic of', 'CO' => 'Colombia', 'CG' => 'Congo',
'CD' => 'Congo, Democratic Republic of', 'CK' => 'Cook Islands', 'CR' => 'Costa Rica',
'HR' => 'Croatia', 'CB' => 'Curacao', 'CY' => 'Cyprus', 'CZ' => 'Czech Republic',
'DK' => 'Denmark', 'DJ' => 'Djibouti', 'DM' => 'Dominica', 'DO' => 'Dominican Republic',
'TL' => 'East Timor (Timor-Leste)', 'EC' => 'Ecuador', 'EG' => 'Egypt', 'SV' => 'El Salvador',
'EN' => 'England', 'GQ' => 'Equatorial Guinea', 'ER' => 'Eritrea', 'EE' => 'Estonia',
'ET' => 'Ethiopia', 'FO' => 'Faroe Islands', 'FJ' => 'Fiji', 'FI' => 'Finland', 'FR' => 'France',
'GF' => 'French Guiana', 'PF' => 'French Polynesia', 'GA' => 'Gabon', 'GM' => 'Gambia',
'GE' => 'Georgia', 'DE' => 'Germany', 'GH' => 'Ghana', 'GI' => 'Gibraltar', 'GR' => 'Greece',
'GL' => 'Greenland', 'GD' => 'Grenada', 'GP' => 'Guadeloupe', 'GU' => 'Guam', 'GT' => 'Guatemala',
'GG' => 'Guernsey', 'GN' => 'Guinea', 'GW' => 'Guinea-Bissau', 'GY' => 'Guyana', 'HT' => 'Haiti',
'HO' => 'Holland', 'HN' => 'Honduras', 'HK' => 'Hong Kong', 'HU' => 'Hungary', 'IS' => 'Iceland',
'IN' => 'India', 'ID' => 'Indonesia', 'IQ' => 'Iraq', 'IE' => 'Ireland, Republic of',
'IL' => 'Israel', 'IT' => 'Italy', 'CI' => 'Ivory Coast', 'JM' => 'Jamaica', 'JP' => 'Japan',
'JE' => 'Jersey', 'JO' => 'Jordan', 'KZ' => 'Kazakhstan', 'KE' => 'Kenya', 'KI' => 'Kiribati',
'KO' => 'Kosrae', 'KW' => 'Kuwait', 'KG' => 'Kyrgyzstan', 'LA' => 'Laos', 'LV' => 'Latvia',
'LB' => 'Lebanon', 'LS' => 'Lesotho', 'LR' => 'Liberia', 'LI' => 'Liechtenstein',
'LT' => 'Lithuania', 'LU' => 'Luxembourg', 'MO' => 'Macau', 'MK' => 'Macedonia',
'MG' => 'Madagascar', 'ME' => 'Madeira', 'MW' => 'Malawi', 'MY' => 'Malaysia',
'MV' => 'Maldives', 'ML' => 'Mali', 'MT' => 'Malta', 'MH' => 'Marshall Islands',
'MQ' => 'Martinique', 'MR' => 'Mauritania', 'MU' => 'Mauritius', 'MX' => 'Mexico',
'FM' => 'Micronesia', 'MD' => 'Moldova', 'MC' => 'Monaco', 'MN' => 'Mongolia', 'MS' => 'Montserrat',
'MA' => 'Morocco', 'MZ' => 'Mozambique', 'NA' => 'Namibia', 'NP' => 'Nepal', 'NL' => 'Netherlands',
'AN' => 'Netherlands Antilles', 'NC' => 'New Caledonia', 'NZ' => 'New Zealand', 'NI' => 'Nicaragua',
'NE' => 'Niger', 'NG' => 'Nigeria', 'NF' => 'Norfolk Island', 'NB' => 'Northern Ireland',
'MP' => 'Northern Mariana Islands', 'NO' => 'Norway', 'OM' => 'Oman', 'PK' => 'Pakistan',
'PW' => 'Palau', 'PA' => 'Panama', 'PG' => 'Papua New Guinea', 'PY' => 'Paraguay', 'PE' => 'Peru',
'PH' => 'Philippines', 'PL' => 'Poland', 'PO' => 'Ponape', 'PT' => 'Portugal', 'PR' => 'Puerto Rico',
'QA' => 'Qatar', 'RE' => 'Reunion', 'RO' => 'Romania', 'RT' => 'Rota', 'RU' => 'Russia',
'RW' => 'Rwanda', 'SS' => 'Saba', 'SP' => 'Saipan', 'SM' => 'San Marino', 'SA' => 'Saudi Arabia',
'SF' => 'Scotland', 'SN' => 'Senegal', 'CS' => 'Serbia & Montenegro', 'SC' => 'Seychelles',
'SL' => 'Sierra Leone', 'SG' => 'Singapore', 'SK' => 'Slovakia', 'SI' => 'Slovenia',
'SB' => 'Solomon Islands', 'ZA' => 'South Africa', 'KR' => 'South Korea', 'ES' => 'Spain',
'LK' => 'Sri Lanka', 'NT' => 'St. Barthelemy', 'SW' => 'St. Christopher', 'SX' => 'St. Croix',
'EU' => 'St. Eustatius', 'UV' => 'St. John', 'KN' => 'St. Kitts & Nevis', 'LC' => 'St. Lucia',
'MB' => 'St. Maarten', 'TB' => 'St. Martin', 'VL' => 'St. Thomas', 'VC' => 'St. Vincent & the Grenadines',
'SR' => 'Suriname', 'SZ' => 'Swaziland', 'SE' => 'Sweden', 'CH' => 'Switzerland', 'SY' => 'Syria',
'TA' => 'Tahiti', 'TW' => 'Taiwan', 'TJ' => 'Tajikistan', 'TZ' => 'Tanzania', 'TH' => 'Thailand',
'TI' => 'Tinian', 'TG' => 'Togo', 'TO' => 'Tonga', 'ZZ' => 'Tortola', 'TT' => 'Trinidad & Tobago',
'TU' => 'Truk', 'TN' => 'Tunisia', 'TR' => 'Turkey', 'TM' => 'Turkmenistan', 'TC' => 'Turks & Caicos Islands',
'TV' => 'Tuvalu', 'UG' => 'Uganda', 'UA' => 'Ukraine', 'UI' => 'Union Island', 'AE' => 'United Arab Emirates',
'GB' => 'United Kingdom',  'US' => 'United States', 'UY' => 'Uruguay', 'UZ' => 'Uzbekistan',
'VU' => 'Vanuatu', 'VA' => 'Vatican City', 'VE' => 'Venezuela', 'VN' => 'Vietnam', 'VR' => 'Virgin Gorda',
'VG' => 'Virgin Islands, British', 'VI' => 'Virgin Islands, US', 'WL' => 'Wales', 'WF' => 'Wallis & Futuna Islands',
'WS' => 'Western Samoa', 'YA' => 'Yap', 'YE' => 'Yemen', 'ZM' => 'Zambia', 'ZW' => 'Zimbabwe');
?>